import BackToTopButton from "@/components/BackToTop/BackToTop";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Blog Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <Providers>{children}</Providers>
        <Footer></Footer>
        <BackToTopButton></BackToTopButton>
      </body>
    </html>
  );
}
